epiverse-trace/packagetemplate

.github/workflows/render_readme.yml

The change done in #12 causes issue when `man/figures/` doesn't exist. See https://github.com/epiverse-trace/etdev/actions/runs/3629893234/jobs/6122615621.

Fix render_readme when man/figures/ doesn't exist

---

.github/workflows/R-CMD-check.yaml

to make
```r
start <- 1:2
start:10
```
an error instead of a warning

Add new _R_CHECK_LENGTH_COLON variable

---

.github/workflows/pkgdown.yaml

To avoid keeping stale files, such as deleted vignettes

Clean pkgdown website on release

---

.lintr

As of lintr 3.1.0, this specific linter is unstable and will generate false-positives and conflicts will styler.

Disable indentation_linter

---

.gitattributes

To avoid having repos classified at TeX when we use long bib files.
More info: https://devguide.ropensci.org/grooming.html#github-linguist

Ignore bibtex files in repo language stats

---

.lintr

Since packages used in `data-raw/` do not need to be listed in `DESCRIPTION`.

Exclude some linters from data-raw/

---

.lintr

Should fix https://github.com/epiverse-trace/.github/issues/17.
@pratikunterwegs @bahadzie could you give it a try please?

Add RcppExports.R to lintr exclusion list

---

vignettes/design-principles.Rmd

This PR removes Contribute section of `design-principles.Rmd` as suggested in #97.

Remove contribute section of design vignette

---

.github/workflows/render_readme.yml
.github/workflows/update-citation-cff.yaml

Should fix #108 
Tested in https://github.com/epiverse-trace/testpkg/actions/workflows/render_readme.yml. It is indeed triggered by pushes by not by releases.

Test alternative approach to not trigger on releases

---

DESCRIPTION

This PR adds myself as a contributor into the template, for easy inclusion (and removal) upon using the template.
I added myself as contributor (`ctb`) but if this should be author (`author`) let me know and I'll update accordingly.

Add Chris as contributor

---

DESCRIPTION

Hi 👋 I noticed while reviewing the `vaccineff` package that there were issues with the URLs from the website. More specifically, the URLs look like this: `https://orcid.org/https://orcid.org/0000-0002-8165-3198` (see also https://github.com/epiverse-trace/vaccineff/issues/39)
It seems like the template is prescribing a faulty (and inconsistent) way to include ORCIDs. This PR updates the template description accordingly.

Remove ORCID domains from `DESCRIPTION`

---

.github/workflows/update-copyright-year.yml

This PR adds a workflow to automatically open PRs to update the license year. This helps prevent these from becoming outdated.
Currently it would run at 03.00AM on January 1st ([`0 3 1 1 *`](https://crontab.guru/#0_3_1_1_*)), which we can adjust if we want. The current text would read:
***
This PR updates the copyright license for this new year! If you're reading this while you're celebrating, enjoy! Don't worry about this one :blush:
***
I am not 100% sure this will run as expected as I don't have everything installed to test this locally beforehand. It is an extension of what we use @libscie, adjusted to handle both LICENSE files present in the template.

Add license year workflow

---

.github/workflows/update-citation-cff.yaml

This PR isolates the action to update the `CITATION.cff`. It is run whenever the relevant files change on the main branch, and creates a pull request if anything changed. 
This was previously discussed in #128 - I tested it as well on a [test repo](https://github.com/chartgerink/testpkg/actions/runs/8077066099).

Isolate citation updates into their own PRs

---

.github/workflows/lint-changed-files.yaml
.github/workflows/update-copyright-year.yml

This PR updates the GitHub actions workflow files that were still using `actions/checkout@v3` which triggers a deprecation warning: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20...` to use `@v4`.
This PR does not contain any breaking changes.

Use `actions/checkout@v4` for all workflows

---

.Rbuildignore
.gitignore

This PR adds `/doc/` and `/Meta/` directories to `.gitignore` and `.Rbuildignore` files. These two directories are produced from `devtools::build_vignettes()`.
This PR does not introduce any breaking changes (assuming nobody in the organisation is using these directories as part of their build process or linking to them on GitHub).

Add vignette building to `.gitignore` and `.Rbuildignore`

---

.github/settings.yml

We recently installed [the GitHub settings application](https://probot.github.io/apps/settings/) to the `epiverse-trace` organization. This PR adds the relevant `.github/settings.yml` file that will then become part of any future repo's built on the template.
This PR **must** be reviewed, as it also has consequences for this repository that need to be resolved first (see below). The settings are my first best guess as to what we want, based on existing settings from the repositories that I investigated. These are only a departure point for our discussion here 💙

Add `.github/settings.yml`

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION

We cannot claim we support a specific R version if we don't test it. By default and per the blueprints, all Epiverse packages should at a minimum support `oldrel-4`. If maintainers of specific packages want to support older version, it's their responsibility to tweak the workflow accordingly.

Add R CMD check on oldest supported R version

---

tests/testthat/helper-state.R

This is a proposed fix for #163.

Only inspect a subset of par() in helper-state

---

.lintr

Fix #171
The `.lintr` needs to be copied in the repositories you maintain to see the effect of this change.

Remove deprecated linter

---

.lintr

These linters are very opinionated and likely to cause a lot of issues in our current codebases.
I still think the `object_overwrite_linter` is good in principle but probably too opinionated and with a benefit limited to very specific scenarios to be worth enforcing by default (at least at this time).
Based on a chat at the development meeting yesterday, there seemed to be an agreement these are the most controversial linters.

Disable some dev linters

---

.Rbuildignore
.gitignore

Gitignore & Rbuildignore files used during release process

---

.github/workflows/lint-changed-files.yaml
.lintr

So etdev can be archived to reduce the organization maintenance load

Get rid of etdev in lintr workflow
