- .gitignore
Fixes #1
Manual import using:
```
wget https://raw.githubusercontent.com/github/gitignore/main/R.gitignore
rm .gitignore
mv R.gitignore .gitignore
```
> Use R.gitignore from github/gitignore

- README.Rmd
- README.md
Fixes #3 by adding to `README.Rmd` and `README.md` (via devtools::build_readme)
> Add CLI commands for package and repo setup

- README.Rmd
As suggested in https://github.com/epiverse-trace/epiparameter/issues/110#issuecomment-1464346371
> add mention to the university or similar to intro paragraph in README

- DESCRIPTION
The title above is self-explanatory.
> Add James Azam's details

- README.Rmd
- README.md
To avoid CRAN note about redirects
> Update link to MIT license

- .lintr
> Add etdev as a linter source package

- DESCRIPTION
I added myself as an author in the DESCRIPTION file and added a vignette section in the README. Note that the later is a proposition that people can amend on.
> add author Karim

- tests/testthat/helper-state.R
> Set testthat state inspector

- .github/workflows/render_readme.yml
- .github/workflows/update-citation-cff.yaml
As discussed in https://epiforecasts.io/posts/2022-04-11-robust-actions/
Thanks @joshwlambert for the report!
> Pull before pushing in workflows

- DESCRIPTION
Fix #78
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
> Run testthat in parallel

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/test-coverage.yaml
> Add merge_group as workflow trigger

- .Rbuildignore
- .github/workflows/R-CMD-check.yaml
- tests/testthat.R
- tools/check.env
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
> Make R CMD check warnings and notes visible on CI

- .github/workflows/dependency-change.yaml
Copied from https://github.com/epiverse-trace/.github/blob/0aa13cc72aeb23b032ea3a43eaa5bd08a87e871f/workflows/dependency-change.yaml.
> Add workflow for dependency changes analysis

- .lintr
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
* **What is the current behavior?** (You can also link to an open issue here)
* **What is the new behavior (if this is a feature change)?**
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
* **Other information**:
> Add linting exclusion for R/stanmodels.R

- tests/testthat/helper-state.R
Following discussions in https://github.com/epinowcast/epinowcast/pull/402.
> Add test on R version to state inspector

- .github/workflows/pkgdown.yaml
- README.Rmd
- README.md
Fix #102
@pratikunterwegs, would you like to test this PR or should I go ahead and merge it?
> Check local links before deploying

- R/dev-utils.R
> Add release note to ensure contributors are acknowledged

- .github/workflows/R-CMD-check.yaml
- tools/check.env
> Move _R_CHECK_LENGTH_COLON_ var to check.env

- tools/check.env
> Fix issue #119 about GNU make NOTE

- .github/workflows/lint-changed-files.yaml
Follow up from https://github.com/r-lib/lintr/pull/2555.
> Force cyclocomp installation in lintr workflow

- DESCRIPTION
- inst/WORDLIST
- man/packagetemplate-package.Rd
Updates the Authors@R field in DESCRIPTION
> chore: update DESCRIPTION Authors@R
